server:
  port: 8080

logging:
  level:
    com.mrtrakwon.zuulv1: debug

zuul:
  routes:
    target1:
      path: /target1/**
      url: http://localhost:7001
      stripPrefix: true
    target2:
      path: /target2/**
      url: http://localhost:7002
      stripPrefix: true

